version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount your Prometheus configuration file
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090
    networks:
      prometheus-net:
        aliases:
          - prometheus

networks:
  prometheus-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: custom_prometheus_bridge
